---
abstract: 'Alien wrapper for NSS ( Network Security Services )'
author:
  - 'Bernhard Amann <bernhard@icsi.berkeley.edu>'
build_requires: {}
configure_requires:
  Alien::Base: '0.003'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: mozilla
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-NSS
provides:
  Alien::NSS:
    file: lib/Alien/NSS.pm
    version: '0.14'
requires:
  Alien::Base: '0.003'
  File::ShareDir: '1.00'
  perl: v5.8.1
resources:
  license: http://opensource.org/licenses/mozilla1.1.php
version: '0.14'
