---
abstract: 'Alien wrapper for NSS ( Network Security Services )'
author:
  - 'Bernhard Amann <bernhard@icsi.berkeley.edu>'
build_requires: {}
configure_requires:
  Alien::Base: 0.001
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-NSS
provides:
  Alien::NSS:
    file: lib/Alien/NSS.pm
    version: 0.03_3
requires:
  Alien::Base: 0
  File::ShareDir: 1.00
  perl: v5.8.1
resources:
  license: http://www.mozilla.org/MPL/MPL-1.1.txt
version: 0.03_3
