---
abstract: 'Alien wrapper for NSS ( Network Security Services )'
author:
  - 'Johanna Amann <johanna@icir.org>'
build_requires: {}
configure_requires:
  Alien::Base: '0.003'
  Module::Build: '0.38'
  Test::More: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.141170'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-NSS
provides:
  Alien::NSS:
    file: lib/Alien/NSS.pm
    version: '0.18'
requires:
  Alien::Base: '0.003'
  File::ShareDir: '1.00'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/0xxon/alien-nss/issues
  homepage: https://github.com/0xxon/alien-nss
  license: http://www.mozilla.org/MPL/MPL-1.1.txt
  repository: https://github.com/0xxon/alien-nss.git
version: '0.18'
